name: ali_muntaser_final_project
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.6.7+11
  provider:
  toast:
  flushbar: ^1.10.4
  carousel_slider: ^2.3.1
  splashscreen: ^1.3.5
  page_view_indicator: ^2.0.4
  intl: 0.16.1
  shared_preferences: ^0.5.12+4

  flutter_bloc:
  equatable:
  flutter_calendar_carousel: ^1.5.2
  font_awesome_flutter:
  line_icons:
  google_fonts:
  simple_animations:
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
  firebase_storage: "^5.0.0-dev.3"
  firebase_messaging:
#  horizontal_data_table:
  json_table:
  firebase_auth:
  dropdown_search: ^0.4.9
#  flutter_zoom_drawer:
  month_picker_dialog:
  path:
  flutter_switch:
  circular_check_box: ^1.0.4
  fradio: ^1.0.1
  fab_circular_menu: ^1.0.0

  syncfusion_flutter_datagrid:
  responsive_table: ^0.1.1+8

  fancy_bottom_navigation:
  circular_profile_avatar:
  pedometer:
  flutter_local_notifications: ^4.0.1+2
  http:
  syncfusion_flutter_charts:
  animated_text_kit:
  otp_screen:
  awesome_dialog: ^1.3.2
  giffy_dialog:
  fl_chart:
  firebase_database:
  percent_indicator: ^1.0.14
  flutter_chat_bubble:
  flipping_card: ^0.0.3
  fancy_on_boarding:
  bubble_chart:
  sliding_card: ^0.1.2
  tab_indicator_styler: ^1.0.0
  modal_bottom_sheet:
  flutter_custom_clippers: ^1.1.2
  cupertino_icons: ^1.0.0
  rotated_corner_decoration: ^1.0.2
  custom_switch:
  getwidget: ^1.2.4
  sticky_headers: ^0.1.8+1
  cool_alert: ^1.0.3
  folding_cell:
  flutter_staggered_animations: "^0.1.3"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  image_path: "dev_assets/logo.jpg"

flutter:


  uses-material-design: true


  # fonts:
  #   - family: RobotoCondensed
  #     fonts:
  #       - asset: assets/fonts/font2/RobotoCondensed-Bold.ttf
  #         weight: 900

  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/logo.png
    - assets/images/clock.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/login1.png
    - assets/images/food.png
    - assets/images/food2.png
    - assets/images/icon_dose.png
    - assets/images/icon_dalyreading.png
    - assets/images/p1.png
    - assets/images/p2.png
    - assets/images/p3.png
    - assets/images/p4.png
    - assets/images/p5.png
    - assets/images/p6.png
    - assets/images/p7.png
    - assets/images/p8.png
    - assets/images/p9.png
    - assets/images/p10.png
    - assets/images/p11.png
    - assets/images/p12.png
    - assets/images/p13.png
    - assets/images/doctor.png
